version: "3.2"
services:
  # server1:
  #   image: httpd:2.4
  # server2:
  #   image: httpd:2.4
  proxy:
    image: nginx
    volumes:
      - ./data/proxy/conf.d:/etc/nginx/conf.d
      - ./data/proxy/share/don:/usr/share/nginx/don
      # - ./data/proxy/log:/var/log/nginx
    ports:
    - "80:80" 